name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage

    - name: Run tests with coverage
      env:
        PYTHONPATH: ${{ github.workspace }}/src
      run: |
        python tests/test_addition.py

    - name: Download SonarScanner
      run: |
       wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.2.0.1873-linux.zip
       unzip sonar-scanner-cli-4.2.0.1873-linux.zip

    - name: Run SonarScanner Analysis
      run: |
       export SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}
       sonar-scanner-4.2.0.1873-linux/bin/sonar-scanner \
       -Dsonar.sources=src \
       -Dsonar.analysis.mode=preview
