name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Install SonarScanner
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk
        wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.12008-linux.zip
        unzip sonar-scanner-cli-4.8.0.12008-linux.zip
        
    - name: SonarCloud Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        sonar-scanner-4.8.0.12008-linux/bin/sonar-scanner -Dsonar.projectKey=python-test-github-actions -Dsonar.organization=deepti-shitole
         -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io
        
        

    - name: Run tests
      run: |
        cd src
        python -m pytest addition.py
        
