name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install coverage  # Install coverage

    - name: Run tests
      run: |
        cd src
        pytest test_addition.py

    - name: Generate coverage report
      run: |
        cd src
        coverage run --source=. -m pytest test_addition.py
        coverage xml -o coverage.xml  # Generate XML coverage report

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: src/coverage/  # Corrected path for uploading coverage report
      if: always()
