name: Build Docker Image

on:
  push:
    branches:
      - main  # or the branch you want to trigger the build on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t my-python-app1 .
